/**
 * SweetCake Admin Orders & Escrow Mock Data
 */

export const INITIAL_ADMIN_ORDERS = [
  {
    id: 'ORD-2025-9982',
    orderType: 'rfq',
    orderTypeLabel: 'AI Custom RFQ',
    time: '10:15 - Hôm nay',
    customerName: 'Chị Hân Mai',
    customerAddress: 'Căn hộ 18.04, Tháp Opal, Saigon Pearl, Bình Thạnh',
    customerPhone: '0918 ••• 567',
    vendorName: 'La Crème Pâtisserie',
    chef: 'Chef Jean-Luc',
    cakeTitle: 'Bánh Sinh Nhật Pikachu Tạo Hình 3D (2 Tầng)',
    cakeSpec: '2 Tầng (20cm + 14cm) • Chiffon Vani Dâu Tây Hữu Cơ',
    cakePriceFormatted: '950.000đ',
    cakePrice: 950000,
    cakeImage:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDl7eAPfu8ECgjGE4u7J5mfocv80iKgNlY1KhInqVxv-hjR5O1WFAa3x79hXqQhZN3RzfJ33wSPB0UKdouIsRpP13PgfleKx3mCShMDqV2rZVoiWnYGmSN7G4E0-D7CFYm5j5rpDndvQ3n1fV4YZICJJmac5TTLXpW80iIIepS9i-MaUDXTEYbRmI-jbI0Rfv0jZk9NELClAHgLk1Vl7QzP8IxXVqOMm28H2jPrOr_TpdRh8EhWTrhJ',
    progressStage: 'baking',
    stageLabel: 'Nướng & Hoàn thiện Pikachu 3D',
    stageStep: 'Giai đoạn 2/4',
    progressPercent: 55,
    telemetryInfo: 'Gắn tai & đuôi sấm sét socola Bỉ',
    escrowStatus: 'locked',
    escrowStatusLabel: 'Khóa Cọc 100%',
    escrowContractId: 'Ví Smart Contract #882',
    escrowPledge: '950.000đ',
    isDelivered: false,
    deliveryVehicle: null,
  },
  {
    id: 'ORD-2025-9975',
    orderType: 'rfq',
    orderTypeLabel: 'AI Custom RFQ',
    time: '09:40 - Hôm nay',
    customerName: 'Anh Tuấn Kiệt',
    customerAddress: 'Tầng 38, Landmark 81, Bình Thạnh',
    customerPhone: '0913 ••• 991',
    vendorName: 'The Sweet Art Boutique',
    chef: 'Bếp Trưởng Mina Trương',
    cakeTitle: 'Điêu Khắc Nghệ Thuật 3D',
    cakeSpec: 'Cốt Earl Grey Cam Yuzu • 20cm',
    cakePriceFormatted: '3.850.000đ',
    cakePrice: 3850000,
    cakeImage:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDW9YG_C2M9nJ2MFdOlxALvM_K-6pVWLgUkquU_KJ71ZXPYWGh4OQIFkANb-D_vZSHb_nvTLgszauPcOjeF16R09lmecxSXcM_9ddEq7DhTxr_fMrsdQnCOYi3hJudwfEfcrZE5y4VMQSV9cTHWiAJX7rDF15RWEE_T4zStVxudoUvsh7PMm0b4Lk-2tZNRT12cFiGGxHZW638CDG-rPVfKKVcLnMFeJPpwBAuzROA2ugxm_rd6JwDn',
    progressStage: 'delivering',
    stageLabel: 'Xe lạnh 4.8°C (Sweet-SH02)',
    stageStep: 'Giai đoạn 3/4',
    progressPercent: 82,
    telemetryInfo: 'Khoang lạnh ISO 4°C - 6°C • Đến sau 12p',
    escrowStatus: 'waiting_release',
    escrowStatusLabel: 'Chờ Khách Nhận',
    escrowContractId: '3.850.000đ đóng băng',
    escrowPledge: '3.850.000đ',
    isDelivered: false,
    deliveryVehicle: 'Xe Van Suzuki Carry (51D-892.44) • 4.8°C',
  },
  {
    id: 'ORD-2025-9968',
    orderType: 'catalog',
    orderTypeLabel: 'Catalog',
    time: '08:15 - Hôm nay',
    customerName: 'Hoàng Phương',
    customerAddress: '182 Lê Duẩn, Quận 1',
    customerPhone: '0977 ••• 442',
    vendorName: 'Maison De Mousse',
    chef: 'Bếp Trưởng Thanh Hà',
    cakeTitle: 'Set Entremet 12 Phần',
    cakeSpec: 'Hộp Quà Cao Cấp Gỗ Sồi',
    cakePriceFormatted: '1.450.000đ',
    cakePrice: 1450000,
    cakeImage:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAoN9aip9TqmUD64z04AxMMQwLT18DbpPJKe_sSdzGXPCMrTRYRp0CcILMSFn4tZr1kJ_PMJdYPQkithDUEenTPwaVsDa0hGAVPo7rqLGVqz2B_fF4N5gNIqzugWx5JRWDf5-L3Gx9MemK_ugUO1jb3GR_k8Yll5CirYwq79YtDPoNf5QUk3af5Oj89Wz59UmyTuwJrNJsZ4PODcC_qjfR8LeCFfwJ46yNj8L5PZ1RzXVhoNwX6yU86',
    progressStage: 'completed',
    stageLabel: 'Đã Bàn Giao (10:02)',
    stageStep: 'Hoàn tất 100%',
    progressPercent: 100,
    telemetryInfo: 'Khách nghiệm thu 5 sao, nguyên vẹn',
    escrowStatus: 'released',
    escrowStatusLabel: 'Đã Giải Ngân',
    escrowContractId: 'Cộng ví xưởng 1.305.000đ',
    escrowPledge: '1.450.000đ',
    isDelivered: true,
    deliveryVehicle: null,
  },
  {
    id: 'ORD-2025-9954',
    orderType: 'rfq',
    orderTypeLabel: 'AI Custom RFQ',
    time: '07:50 - Hôm nay',
    customerName: 'Quang Thịnh Event Co.',
    customerAddress: 'GEM Center, 8 Nguyễn Bỉnh Khiêm, Q.1',
    customerPhone: '0938 ••• 888',
    vendorName: 'ChocoLuxe Master',
    chef: 'Bếp Trưởng Antoine V.',
    cakeTitle: 'Tháp Macaron & Tartlet',
    cakeSpec: 'Bộ Tháp 6 Tầng • 120 chiếc',
    cakePriceFormatted: '4.600.000đ',
    cakePrice: 4600000,
    cakeImage:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC2jVxut1zzwGlXrX5Qd2x2WNBT6rUBubBUtzP_i1qxtqf5_2dbi7ioPFDAVsuoZ8SKoHT7tLD4tns5iTZbmyp8ZTwgFvSkRiz5o0z4DS41fa05B4e8-hDbmFc23RxVnOBMhSnFMcS6rKmTkZzDuCSrFxCtw4w7Dx35HJ3hSYOvlMyuEei7BGqW-wHRRLJn2oMqOtzZW-pPLtMvG9n212OsYalf7ShAZqiH4zpJKrsBas7kovqvufWF',
    progressStage: 'baking',
    stageLabel: 'Đang nướng & ghép tháp',
    stageStep: 'Xưởng hoàn tất 60%',
    progressPercent: 60,
    telemetryInfo: 'Giờ giao hẹn: 15:30 chiều',
    escrowStatus: 'locked',
    escrowStatusLabel: 'Khóa Cọc 100%',
    escrowContractId: '4.600.000đ Escrow an toàn',
    escrowPledge: '4.600.000đ',
    isDelivered: false,
    deliveryVehicle: null,
  },
  {
    id: 'ORD-2025-9970',
    orderType: 'catalog',
    orderTypeLabel: 'Catalog',
    time: '09:10 - Hôm nay',
    customerName: 'Chị Thu Trang',
    customerAddress: 'Sunrise City, Nguyễn Hữu Thọ, Q.7',
    customerPhone: '0982 ••• 115',
    vendorName: 'La Crème Pâtisserie',
    chef: 'Bếp Trưởng Pierre N.',
    cakeTitle: 'Nhung Đỏ Velvet 16cm',
    cakeSpec: 'Mứt Mâm Xôi & Cream Cheese',
    cakePriceFormatted: '520.000đ',
    cakePrice: 520000,
    cakeImage:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBkMxWXfx10-WWspjaw1meUeUzdn5KwGiUOyDqbeKnpTSQQyCNpLeD8Q8H7ljRvkYgwfk0-7RZAax3Nsl9nOfDTZY6ihrBdnUGEGeylP6iGn2gkGmCftzbRvXb4zCLQ74N_vnN9E1KLMxNSe348mMvSZNgpyyBVxEdRkOq_NdnH7nZtGCfkKHdXRXWKFWR7wl7biO53Rh471767CCnFVNv9z0L_lYZfkql-OSISNANs32vtoiqnfLcO',
    progressStage: 'baking',
    stageLabel: 'Đang phủ mứt & decor',
    stageStep: 'Giai đoạn 3/4',
    progressPercent: 75,
    telemetryInfo: 'Làm lạnh cấp tốc trước khi ship',
    escrowStatus: 'locked',
    escrowStatusLabel: 'Khóa Cọc 100%',
    escrowContractId: 'Bảo vệ thanh toán',
    escrowPledge: '520.000đ',
    isDelivered: false,
    deliveryVehicle: null,
  },
  {
    id: 'ORD-2025-9941',
    orderType: 'rfq',
    orderTypeLabel: 'AI Custom RFQ',
    time: '06:30 - Hôm nay',
    customerName: 'Cặp đôi Hoàng & Mai',
    customerTier: 'TIỆC CƯỚI HAUTE',
    customerAddress: 'Park Hyatt Saigon, Q.1',
    customerPhone: '0903 ••• 678',
    vendorName: 'La Crème Pâtisserie',
    chef: 'Bếp Trưởng Pierre N.',
    cakeTitle: 'Rustic Floral 3 Tầng',
    cakeSpec: 'Vani Madagascar & Việt Quất',
    cakePriceFormatted: '2.450.000đ',
    cakePrice: 2450000,
    cakeImage:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCVn2OrQKD9lH_3S3Os_i8iDt3_GsKUy8nP8136M6B7FTZ7Lb1y4-J73EXLaZmgdPTauMCeer3bV3wDxytfXntISInDv55-ZVldUO5SJvcGgPcG9Tsi5Z4j9OuTGt5PJw3NL70eYq8jb0LRID5BkDivJiilcaCkNA8X8QXfE9EEFgrk2HTvCuINUPJQGswULdnBjAZHymjSj51Tbloh-qgoH5pqm-YrofYGGatioA9yNR8HQO5d1XaL',
    progressStage: 'delivering',
    stageLabel: 'Xe lạnh 4.5°C (Sweet-SH09)',
    stageStep: 'Giai đoạn 3/4',
    progressPercent: 88,
    telemetryInfo: 'Chống rung Shock-absorber • Đến sau 5p',
    escrowStatus: 'waiting_release',
    escrowStatusLabel: 'Khóa Cọc',
    escrowContractId: '2.450.000đ giải ngân sau giao',
    escrowPledge: '2.450.000đ',
    isDelivered: false,
    deliveryVehicle: 'Xe Van Suzuki Carry (51D-610.22) • 4.5°C',
  },
]
;

export const MOCK_ADMIN_ORDERS = INITIAL_ADMIN_ORDERS;
export const MOCK_ORDERS = INITIAL_ADMIN_ORDERS;
