/**
 * SweetCake Admin Users Mock Data
 */

export const INITIAL_USERS = [
  {
    id: 'CUST-9821',
    name: 'Mai Lan',
    email: 'mailan.luxury@gmail.com',
    phone: '0903 882 119',
    maskedPhone: '0903 ••• 882 (Q.1, TP.HCM)',
    location: 'Quận 1, TP.HCM',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCZPxXa22XB0i3Vu6CEjC4sV8mvBIFb0EQEZcnrvSuK1DEWprPNIp8PkP71WcMVzOLDX6K-Jt8VTcnRELtaaMv9rnSZgPT4TmpW-whaHgBMbbNYkdUSCvSRluMe7lpAnau4QdozHVyKUzc-cOkYvDDtR1JZmBfJhvyyBetI1iwKFIecoBb2W-UPkWCRuIRrrqOITaESSKPbN_PRkwFhA-JKj3ye8RLhRYTIvA4UBkobMHm1hSVvheCw',
    tier: 'diamond',
    tierLabel: 'Khách Doanh Nghiệp',
    gmv: 34500000,
    gmvFormatted: '34.500.000 ₫',
    ordersCount: 18,
    ordersLabel: '18 đơn hoàn tất',
    recentCake: 'Bánh sinh nhật Pikachu 2 tầng',
    recentDate: '12/05/2024 · Atelier Le Sucre',
    status: 'active',
    trustScore: 100,
    trustLabel: 'Bảo chứng tuyệt đối',
    isStar: false,
    tasteNotes: 'Ưa chuộng cốt Chiffon vani giảm ngọt 30%, bơ Thụy Sĩ',
  },
  {
    id: 'CUST-8412',
    name: 'Tuấn Kiệt',
    email: 'kiet.tuan.dev@outlook.com',
    phone: '0918 301 445',
    maskedPhone: '0918 ••• 301 (Q.3, TP.HCM)',
    location: 'Quận 3, TP.HCM',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC8HY7hXfIRFC6x_FtTIDcdiKYeVz2YhOsr0SAsjo80KEwVctPiMaiRnJ9A3OQtabvmkqHDfN2jWVuH3_NZ0NY_IYJ5k-GUBcwi9ItHRUoj6Fd4-QXKNoMwsdBnW3A7Wf11lc7VEoqsPoagf8lsUojiMIPdgJjRifAM3Zm5c_Y-8U79rSwEFmwMqIAldUoOh9a1eWiy2iy-zn7EGi-OUPgiKqLkEEumpvTzlec3wyJoFPsVjtrdFMhq',
    tier: 'gold',
    tierLabel: 'Khách Đặt Tiệc',
    gmv: 19800000,
    gmvFormatted: '19.800.000 ₫',
    ordersCount: 12,
    ordersLabel: '12 đơn hoàn tất',
    recentCake: 'Parisian Earl Grey Mousse',
    recentDate: '08/05/2024 · Maison de Fleur',
    status: 'active',
    trustScore: 99,
    trustLabel: 'Xuất sắc',
    isStar: false,
    tasteNotes: 'Thích dòng bánh Mousse lạnh Pháp vị trà Earl Grey & Macaron',
  },
  {
    id: 'CUST-7210',
    name: 'Thu Trang',
    email: 'thutrang.arch@gmail.com',
    phone: '0972 194 662',
    maskedPhone: '0972 ••• 194 (Tây Hồ, Hà Nội)',
    location: 'Tây Hồ, Hà Nội',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBPhk3zOBZD8Cr2zOBmcEGMAcyQJu6Dy84ryWVBO22fX3mS9_K9Q-zyp1W5B1elP41XST-5EKSk1cpn7HAY-Q6kQ_WArwyoR098t1GnG6YGsTnJeQIQr_PjqtYwdt0jl5kumQKUwPrFmOB5IcoK81Oyfom9eVQX24hxN9eZvcPaSAZcQTv9PtSUchTfgKuryUhzfSLe4O8x7rvgtPXuuTCIAHGkjxbEdUjHoGTauCltmZxUXfXISi-X',
    tier: 'gold',
    tierLabel: 'Khách Đặt Tiệc',
    gmv: 14200000,
    gmvFormatted: '14.200.000 ₫',
    ordersCount: 9,
    ordersLabel: '9 đơn hoàn tất',
    recentCake: 'Velvet Raspberry Bliss',
    recentDate: '02/05/2024 · Pâtisserie Lumière',
    status: 'active',
    trustScore: 98,
    trustLabel: 'Rất cao',
    isStar: false,
    tasteNotes: 'Ưa chuộng dòng Velvet & Trái cây mọng tươi',
  },
  {
    id: 'CUST-6104',
    name: 'Hoàng Anh',
    email: 'hoanganh.art@gmail.com',
    phone: '0898 551 228',
    maskedPhone: '0898 ••• 551 (Bình Thạnh, TP.HCM)',
    location: 'Bình Thạnh, TP.HCM',
    avatar: null,
    avatarInitials: 'HA',
    tier: 'silver',
    tierLabel: 'Khách Cá Nhân',
    gmv: 4850000,
    gmvFormatted: '4.850.000 ₫',
    ordersCount: 5,
    ordersLabel: '5 đơn hoàn tất',
    recentCake: 'Bento Cake Hàn Quốc',
    recentDate: '28/04/2024 · Little Seoul Bakery',
    status: 'active',
    trustScore: 95,
    trustLabel: 'Tích cực',
    isStar: false,
    tasteNotes: 'Đặt bánh Bento phong cách vintage mini & thiệp tay',
  },
  {
    id: 'CUST-5519',
    name: 'Hoàng & Mai',
    email: 'hoangmai.wedding@gmail.com',
    phone: '0909 773 991',
    maskedPhone: '0909 ••• 773 (Q.7, TP.HCM)',
    location: 'Quận 7, TP.HCM',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC_I4A2mp98jQyTqZqwM3W6Z2jpfBpk6EQVXAdZpbr2Gd83A0X0T9XqAUJD9s13Q7-gwB8l01QMgDvkyEVpK5QwY3xAv5qrfVwf7byiY1P75H6KNN7Nf-V3da0ANJpBDQmUOiMjjXQZ4X-63MDSRPrHhr8C7sMpj1osaev1_BUWBuUPal0vizO22JqmpYJ01MZCV-cjpg_XltIpDJ2hS0h8zapxCuS8g9IBPYA7td1owO93l_lAIYak',
    tier: 'diamond',
    tierLabel: 'Khách Doanh Nghiệp',
    gmv: 28600000,
    gmvFormatted: '28.600.000 ₫',
    ordersCount: 7,
    ordersLabel: '7 đơn tiệc cưới',
    recentCake: 'Bánh Cưới Rustic Floral Chiffon 3 tầng',
    recentDate: '24/04/2024 · Le Grand Pastry',
    status: 'active',
    trustScore: 100,
    trustLabel: 'Bảo chứng tuyệt đối',
    isStar: false,
    tasteNotes: 'Khách hàng sự kiện cưới hỏi cao cấp, yêu cầu xe lạnh 4-6°C',
  },
  {
    id: 'CUST-3901',
    name: 'Lê Văn Nam',
    email: 'nam.levan29@gmail.com',
    phone: '0354 912 883',
    maskedPhone: '0354 ••• 912 (Cầu Giấy, HN)',
    location: 'Cầu Giấy, Hà Nội',
    avatar: null,
    avatarInitials: 'LN',
    tier: 'standard',
    tierLabel: 'Khách Hàng Mới',
    gmv: 650000,
    gmvFormatted: '650.000 ₫',
    ordersCount: 1,
    ordersLabel: '1 đơn hoàn tất',
    recentCake: 'Tiramisu Ý truyền thống',
    recentDate: '19/04/2024 · Dolce Vita Hà Nội',
    status: 'active',
    trustScore: 90,
    trustLabel: 'Khách hàng mới',
    isStar: false,
    tasteNotes: 'Khách hàng mới đăng ký qua ứng dụng, ưa chuộng Tiramisu',
  },
  {
    id: 'CUST-2180',
    name: 'Đỗ Minh Khang',
    email: 'khang.do998@gmail.com',
    phone: '0932 419 004',
    maskedPhone: '0932 ••• 419 (Bị gắn cờ vi phạm)',
    location: 'Tân Bình, TP.HCM',
    avatar: null,
    avatarInitials: 'DK',
    tier: 'suspended',
    tierLabel: 'Bị Tạm Khóa',
    gmv: 1200000,
    gmvFormatted: '1.200.000 ₫',
    ordersCount: 3,
    ordersLabel: '3 đơn (2 lần bùng cọc)',
    recentCake: 'Bùng cọc 2 lần liên tiếp tại xưởng',
    recentDate: 'Khóa từ 14/04/2024',
    status: 'suspended',
    trustScore: 42,
    trustLabel: 'Cảnh báo rủi ro',
    isStar: false,
    tasteNotes: 'Vi phạm quy chế đặt cọc Escrow Vault 2 lần liên tiếp',
  },
]
;

export const MOCK_USERS = INITIAL_USERS;
