/**
 * SweetCake Admin Vendors Mock Data
 */

export const INITIAL_VENDORS = [
  {
    id: 'VEND-01',
    name: 'La Crème Pâtisserie',
    chef: 'Chef Jean-Luc',
    location: 'Quận 1, TP.HCM',
    district: 'q1',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBZuHJdgD9s_TE5RWxEokJ5CIukWpDBXpbMZ7tbrbYR-ICJSKehtgQ0SfDAcHx2dqormBHk6uZyje3vsiGEu1uNATAuyJi_Q9f1RkdAwV9dWVMrgU6o5pu8eXDIzghYloQunt4q0bSwCepWk_btyEKhSkCbWcv4SvV9RuoDv1wT-DXpOENx-kR-vAESuUOXnXPCnM9CYIF5NeWNDGUAFd7PkAHYLcbBHf72i8wFHk-Xwe2UOS7Gn7BC',
    categoryTag: 'Haute Pâtisserie Atelier',
    specialty: 'Bánh Lạnh & Entremet Pháp',
    categoryType: 'french',
    legalBadge: 'Đạt ATTP Cấp A',
    certification: 'Le Cordon Bleu Paris',
    revenueFormatted: '145.000.000đ',
    revenueNum: 145000000,
    ordersCount: 186,
    rating: '4.9★',
    slaOnTime: '99.5% đúng hẹn',
    cancellationRate: 'Hủy đơn: 0.2%',
    status: 'active',
    statusLabel: 'Đang mở lò',
    isUrgent: false,
    verified: true,
    takeRate: '5.0%',
    escrowDeposit: '20.000.000đ',
    inspectionPhotos: [
      {
        title: 'Buồng Nướng Công Nghiệp',
        desc: 'Lò Salva Tây Ban Nha 180°C',
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrd6k8AxdXIpcvUew_MOuWPXERmixyGoGEMSbfRrr2D_NjHNcEfpwO6YmdXvHeBa1Z2RngGb9XmrNj0ZOGL3sN-FAYCvXwCJJKfU7Yp8EabBcjG9dEXYq4nYAN23G4LYhRnmY1pXcqZzK_SmfHOwjKhFKTwsm8fdLQNSiVRu6hg9u1GLpNlwMR4ddt5aAHza-WulOSntXT0apE-cvO0trXucNDl7cTwV9HkUHIgfK-5Y15ik_vKmN4',
      },
      {
        title: 'Phòng Lạnh Ráp Bánh Cưới',
        desc: 'Buồng lạnh 16°C định hình mousse',
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZg77AfnTaX4peI3YynMee-I-DcrPyvFY3H0GoucHiBopkRC1ptttt5oVT3RVJOBA00DkaxeO9qQplvKHjruVLhzIzJ6dwM5Sigxpwx88ezXEfuOevJrCBs8nUjDJ7EyNiWtBbBGIO0Ymr-iWlU7u9TJDRdfbfWzdkbBfkUt6gKDvLSSJzQJNFJSvLzbsU6TXlzXAbAeXx-FHC4Bdf7kDCHXhK8Vudtd8z21EMQ9vDUfR6eN1W0Hc0',
      },
    ],
  },
  {
    id: 'VEND-88',
    name: 'Atelier De Gâteau',
    chef: 'Bếp trưởng Monique',
    location: 'Thảo Điền, Quận 2',
    district: 'q2',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCh_YSotcKYmHgfF4pKnUuLtnAuC7anjVBGsyyfmNff0TRsDm3M2--8hpicjhOf37g5IHS7aBzmHUOnzt0BWC5umWsDAc0bPa1bIawdP8VFukAJSQqn6dsNU942VOEhT1NNi-pamzDBQuzg2XX1GeGKIwCLLgbFxeUfk7YKLjpSGBW8KwQH9owYV65R8LAfqPWaXnTgZ-d5KsrxNgJgrY35Wk7vkC-4pXuBM4IgNExz40l2Y_6nzd1g',
    categoryTag: 'Bánh Cưới Haute Couture',
    specialty: 'Đường Nghệ Thuật 3-5 Tầng',
    categoryType: 'couture',
    legalBadge: 'Đạt ATTP Thẩm Định',
    certification: 'GPKD: 0317894211',
    revenueFormatted: 'Hồ sơ mới',
    revenueNum: 0,
    ordersCount: 0,
    rating: 'Mới',
    slaOnTime: 'Chờ thử nghiệm lò',
    cancellationRate: 'Hạn mức: 250M',
    status: 'pending',
    statusLabel: 'Chờ duyệt hồ sơ',
    isUrgent: true,
    verified: false,
    takeRate: '5.0%',
    escrowDeposit: '15.000.000đ',
    inspectionPhotos: [
      {
        title: 'Buồng Nướng Công Nghiệp',
        desc: 'Lò Salva Tây Ban Nha 180°C',
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrd6k8AxdXIpcvUew_MOuWPXERmixyGoGEMSbfRrr2D_NjHNcEfpwO6YmdXvHeBa1Z2RngGb9XmrNj0ZOGL3sN-FAYCvXwCJJKfU7Yp8EabBcjG9dEXYq4nYAN23G4LYhRnmY1pXcqZzK_SmfHOwjKhFKTwsm8fdLQNSiVRu6hg9u1GLpNlwMR4ddt5aAHza-WulOSntXT0apE-cvO0trXucNDl7cTwV9HkUHIgfK-5Y15ik_vKmN4',
      },
      {
        title: 'Phòng Lạnh Ráp Bánh Cưới',
        desc: 'Buồng lạnh 16°C định hình mousse',
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZg77AfnTaX4peI3YynMee-I-DcrPyvFY3H0GoucHiBopkRC1ptttt5oVT3RVJOBA00DkaxeO9qQplvKHjruVLhzIzJ6dwM5Sigxpwx88ezXEfuOevJrCBs8nUjDJ7EyNiWtBbBGIO0Ymr-iWlU7u9TJDRdfbfWzdkbBfkUt6gKDvLSSJzQJNFJSvLzbsU6TXlzXAbAeXx-FHC4Bdf7kDCHXhK8Vudtd8z21EMQ9vDUfR6eN1W0Hc0',
      },
    ],
  },
  {
    id: 'VEND-45',
    name: 'Sweet Mochi & Bento',
    chef: 'Chef Kim Min-seo',
    location: 'Bình Thạnh, TP.HCM',
    district: 'bt',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCwTc_vpyJGghGg0Msi9SvmBDq-EWNW_mad7V8S8BgY69mKCWq8gAg7A_WzA5jRfPBMQCmjEPMIYWApdgkiwMxfvQ9EdDqnYGbnQfBBi2tCuZum6GQMJiGhjMCl3dFW6MV5vaLx4bpaUSeEHsK7VObvMOpLA1ud4GJqdXP-Yim3GiYFv7yC89NHu4IXkeP9Z1IcUZET2QaHzqvs9L9Sfi1uGz07VxJ-SyxGh1JvR1n7PADWtAdR80TN',
    categoryTag: 'Bento Studio Hàn Quốc',
    specialty: 'Bento Vẽ Tay & Daifuku Mochi',
    categoryType: 'korean',
    legalBadge: 'Thiếu ảnh lò nướng',
    certification: 'Hạn chót: 48 giờ',
    revenueFormatted: '64.500.000đ',
    revenueNum: 64500000,
    ordersCount: 110,
    rating: '4.7★',
    slaOnTime: '97.8% đúng hẹn',
    cancellationRate: 'Hủy đơn: 0.9%',
    status: 'needs_info',
    statusLabel: 'Cần bổ sung giấy tờ',
    isUrgent: false,
    verified: false,
    takeRate: '5.5%',
    escrowDeposit: '10.000.000đ',
    inspectionPhotos: [
      {
        title: 'Khu Vực Trang Trí Bento',
        desc: 'Bàn đá marble vệ sinh đạt chuẩn',
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZg77AfnTaX4peI3YynMee-I-DcrPyvFY3H0GoucHiBopkRC1ptttt5oVT3RVJOBA00DkaxeO9qQplvKHjruVLhzIzJ6dwM5Sigxpwx88ezXEfuOevJrCBs8nUjDJ7EyNiWtBbBGIO0Ymr-iWlU7u9TJDRdfbfWzdkbBfkUt6gKDvLSSJzQJNFJSvLzbsU6TXlzXAbAeXx-FHC4Bdf7kDCHXhK8Vudtd8z21EMQ9vDUfR6eN1W0Hc0',
      },
    ],
  },
  {
    id: 'VEND-92',
    name: 'Dark Velvet Pâtisserie',
    chef: 'Chef Eric Vũ',
    location: 'Quận 1, TP.HCM',
    district: 'q1',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDOuoB1YkEmcnOu28QdxPh8PrBoZw6WU8gax7ow8hE0gMD6xJ8-R_v1vTHO8r0X4m7p__Ja6LLbbgOKpgDK9a-iBDe36sW5Kbq37nXat7eOjQN9RbziT_MUglfGzAF5XDVob0D3S9d0eqeXMfCKWxkxg1LH2324NgXF33F6nf9zmR782zUPGa_CIU_2kIs3d5txJsLeo9K8YcqSs-yUpUrdr6QGU1APz3q6SawD_IxKK_RPdwKcy0pM',
    categoryTag: 'Truffle Chocolate & Lạnh',
    specialty: 'Praline Bỉ & Bonbon',
    categoryType: 'french',
    legalBadge: 'Đủ ATTP & ISO 22000',
    certification: 'Haute Pâtisserie Paris',
    revenueFormatted: 'Hồ sơ chờ kích hoạt',
    revenueNum: 0,
    ordersCount: 0,
    rating: 'Mới',
    slaOnTime: 'Đạt test lạnh 5°C',
    cancellationRate: 'Cam kết: 80 đơn/tuần',
    status: 'pending',
    statusLabel: 'Chờ kích hoạt',
    isUrgent: false,
    verified: true,
    takeRate: '5.0%',
    escrowDeposit: '15.000.000đ',
    inspectionPhotos: [
      {
        title: 'Buồng Kiểm Soát Nhiệt Bonbon',
        desc: 'Nhiệt độ ổn định 18°C',
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrd6k8AxdXIpcvUew_MOuWPXERmixyGoGEMSbfRrr2D_NjHNcEfpwO6YmdXvHeBa1Z2RngGb9XmrNj0ZOGL3sN-FAYCvXwCJJKfU7Yp8EabBcjG9dEXYq4nYAN23G4LYhRnmY1pXcqZzK_SmfHOwjKhFKTwsm8fdLQNSiVRu6hg9u1GLpNlwMR4ddt5aAHza-WulOSntXT0apE-cvO0trXucNDl7cTwV9HkUHIgfK-5Y15ik_vKmN4',
      },
    ],
  },
  {
    id: 'VEND-19',
    name: 'The Sweet Art Boutique',
    chef: 'Nghệ nhân Tuấn Anh',
    location: 'Quận 3, TP.HCM',
    district: 'q3',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDNppkk1FPMsGu0KgbpXziGo7GsKeX_0RI2IFw2JTa84suWdPmYgpMdSDs-oA5jlQKLeo0mM07gwukB3YaTJl2_FzqUI3sNFZaMiHl_8Hx9AQ57R0vSJ8ClgvtTBF-XVbQUwhFO4eQVfi9plW-Bt0PATeBuEV4CtBLBuSkKn5Kxz-PzdaKxmsL-VGgXgtjdyKm2sO6cIpNVE44dkWhb2_u4y1Q3qwaUII4nklXNU6ZsTB8aHDEXw93g',
    categoryTag: 'AI Custom 3D & Fondant',
    specialty: 'Nặn Tượng Sinh Nhật Cao Cấp',
    categoryType: 'ai-3d',
    legalBadge: 'Đạt ATTP TP.HCM',
    certification: 'Màu Thực Phẩm FDA US',
    revenueFormatted: '98.000.000đ',
    revenueNum: 98000000,
    ordersCount: 142,
    rating: '4.8★',
    slaOnTime: '99.1% đúng hẹn',
    cancellationRate: 'Hủy đơn: 0.4%',
    status: 'active',
    statusLabel: 'Đang mở lò',
    isUrgent: false,
    verified: true,
    takeRate: '5.0%',
    escrowDeposit: '20.000.000đ',
    inspectionPhotos: [
      {
        title: 'Buồng Tạo Hình Tượng 3D',
        desc: 'Hệ thống lọc khí áp lực dương',
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZg77AfnTaX4peI3YynMee-I-DcrPyvFY3H0GoucHiBopkRC1ptttt5oVT3RVJOBA00DkaxeO9qQplvKHjruVLhzIzJ6dwM5Sigxpwx88ezXEfuOevJrCBs8nUjDJ7EyNiWtBbBGIO0Ymr-iWlU7u9TJDRdfbfWzdkbBfkUt6gKDvLSSJzQJNFJSvLzbsU6TXlzXAbAeXx-FHC4Bdf7kDCHXhK8Vudtd8z21EMQ9vDUfR6eN1W0Hc0',
      },
    ],
  },
  {
    id: 'VEND-33',
    name: 'ChocoLuxe Master',
    chef: 'Chef Hoàng Lâm',
    location: 'Quận 7 Phú Mỹ Hưng',
    district: 'q7',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDtOCSipvmCLMC9cB5nwy6zFTSuJV5EbmnILd1rznkUweYjLYYNysj5nKSHkm5QNKhJ753AY9BZ2QaCuLT_-KAOp-XYUgA44H9tVnzqOeT7h3ecRiO3psRguFbrsEzl-g1MgLufa5qa2fsmhoTUVvFBmeQJlZmmeJZZUF5vW5p2bpGevt-xcOTvb8-TfUcMLz6vMHWLVOP3AzVUROlDRfCaGy4jLdYfmQ9kakIJudG7NHh3azFf5fUJ',
    categoryTag: 'Tháp Macaron & Tiệc Sự Kiện',
    specialty: 'Tartlet & Petit Four Tiệc',
    categoryType: 'macaron',
    legalBadge: 'Đạt ATTP Chuỗi Cung',
    certification: 'Chứng nhận HACCP 2024',
    revenueFormatted: '82.000.000đ',
    revenueNum: 82000000,
    ordersCount: 95,
    rating: '4.9★',
    slaOnTime: '99.8% đúng hẹn',
    cancellationRate: 'Hủy đơn: 0.0%',
    status: 'active',
    statusLabel: 'Đang mở lò',
    isUrgent: false,
    verified: true,
    takeRate: '5.0%',
    escrowDeposit: '25.000.000đ',
    inspectionPhotos: [
      {
        title: 'Dây Chuyền Nướng Vỏ Macaron',
        desc: 'Lò đối lưu đa tầng nhiệt chuẩn',
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrd6k8AxdXIpcvUew_MOuWPXERmixyGoGEMSbfRrr2D_NjHNcEfpwO6YmdXvHeBa1Z2RngGb9XmrNj0ZOGL3sN-FAYCvXwCJJKfU7Yp8EabBcjG9dEXYq4nYAN23G4LYhRnmY1pXcqZzK_SmfHOwjKhFKTwsm8fdLQNSiVRu6hg9u1GLpNlwMR4ddt5aAHza-WulOSntXT0apE-cvO0trXucNDl7cTwV9HkUHIgfK-5Y15ik_vKmN4',
      },
    ],
  },
]
;

export const MOCK_VENDORS = INITIAL_VENDORS;
