/**
 * SweetCake Customer Stores & Partner Bakeries Mock Data
 */

export const STORES = [
  {
    id: 'la-creme-patisserie',
    name: 'La Crème Pâtisserie',
    tagline: 'Chứng nhận Nghệ Nhân Bếp Bánh Pháp',
    badge: 'Top 1 Tiệm Bánh Uy Tín 2024',
    badgeColor: 'bg-secondary text-on-secondary',
    location: '18 Nguyễn Huệ, P. Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    city: 'hcm',
    chef: 'Chef Jean-Luc Laurent & Chef Mai Anh',
    chefRole: 'Master Pâtissier (20 năm kinh nghiệm Le Cordon Bleu Paris)',
    rating: 4.9,
    reviewsCount: 320,
    ordersCount: 1850,
    specialty: 'Entremet cao cấp, 100% bơ Elle & Vire và socola Valrhona Pháp',
    deliverySla: 'Giao xe lạnh 4°C - 6°C chuyên dụng • Nhận đơn trước 4H',
    escrowBadge: 'Bảo chứng cọc SweetCake Escrow 100%',
    image:
      'https://lh3.googleusercontent.com/aida/AEtjO1UW-Pqje1qQ27WocOmEF6z8uQbX4Pu7dER_Li586FmA7D-SZPtELbM4diNLey0TATd7BWeyBRVp0BJyiwRQ_Yj2o8ZvjU1gga_5DYXFHmRARECApBa-Pknbu-F_C4RsJvPsxZur94CVef_-mhMUtBA5pqCBm39qRgn4zALShBi4iNWkPvOaQa9bTIcfaPbq4eDVHCaFKq1lgnsEbgULw4G-0rsbYDlzqjGcSoKiajpNsUeCjPnRs_qaS3o',
    perk: 'Bảo hiểm dáng bánh 100%',
    popularCake: 'Bánh Mousse Trái Cây & Bánh Kem 2 Tầng Cưới',
  },
  {
    id: 'sweet-bakery-studio',
    name: 'Sweet Bakery Studio',
    tagline: 'Bậc Thầy Bánh Tạo Hình AI & Nghệ Thuật 3D',
    badge: 'Tiệm Bánh Sáng Tạo Của Năm',
    badgeColor: 'bg-primary text-secondary-fixed',
    location: '45 Nguyễn Gia Trí, P. 25, Q. Bình Thạnh, TP. Hồ Chí Minh',
    city: 'hcm',
    chef: 'Master Baker Linh Đan & Đội Ngũ Art Decor',
    chefRole: 'Chuyên gia điêu khắc Fondant & Bánh kem 3D nhân vật hoạt hình',
    rating: 4.9,
    reviewsCount: 420,
    ordersCount: 2100,
    specialty: 'Tạo hình bám sát mẫu AI >95%, Cốt Chiffon Nhật Bản mềm ẩm ít ngọt 35%',
    deliverySla: 'Giao hỏa tốc 2H - 3H • Xe máy thùng chống sốc & xe lạnh',
    escrowBadge: 'Bảo chứng cọc SweetCake Escrow 100%',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBwa0x2Pq4PQpZabCVw-oPcl9Kx3AjY8Se4w5V-yM-Cwjrjxd8jba5hv0SPnDkxM_eLtOKLaCNuUDDl6uyQ3slRL0zdoHgazEbhQZgxplLn5ErWpu6LuqSG2cmZUHp2Nrju8F1zOHGfkAEVgsYsLzhyRxlWHDt4rfoMRrrml9EHVVSLAZOB7ORzGf7oOQ614QKeV2tziVXLp5eM7BTdXQBgQysd-nJGwi2Xbb1EPsZ3vM92r3FrOp0B',
    perk: 'Nhận đơn gấp 2H',
    popularCake: 'Bánh Pikachu 3D, Bánh Sinh Nhật Tạo Hình Hoạt Họa',
  },
  {
    id: 'moon-cake-haute',
    name: 'Moon Cake Haute Atelier',
    tagline: 'Bánh Kem Sự Kiện & Tiệc Cưới Haute Couture',
    badge: 'Le Cordon Bleu Certified 5.0★',
    badgeColor: 'bg-amber-600 text-white',
    location: '24 Xuân Thủy, P. Thảo Điền, Quận 2 (TP. Thủ Đức), TP. Hồ Chí Minh',
    city: 'hcm',
    chef: 'Chef Moon (Cựu Bếp Trưởng Khách Sạn 5 Sao Park Hyatt)',
    chefRole: 'Chuyên gia phối hoa tươi ngoại nhập & Dát vàng 24K ăn được',
    rating: 5.0,
    reviewsCount: 310,
    ordersCount: 1450,
    specialty: 'Bánh kem nhiều tầng lộng lẫy, phối Macaron thủ công Pháp',
    deliverySla: 'Xe lạnh chuyên dụng riêng • Nhân viên hỗ trợ setup bàn tiệc tận nơi',
    escrowBadge: 'Bảo chứng cọc SweetCake Escrow 100%',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAbKBS4iuDLDnNj39sedRAM0tSTf90WV0cMtcL1D83J6gCbPWydfHBUx5Vm4AG2wdIJMx0mqVbO5FFktujBONg-xMsmbOSQ-XXqnuTzs_g6OFMgViOgssR3DE9ttoSgkr1Shnt27IVsGw4mZqhmg6xb23szp3_uMuwaK1KAfJwvX-iELmSlnPOkMeTrzZIMJPvIe7VjLNP4s2781KDXemDfKkBVq2wtMqZS8e_AAubIg9VZCOc8z-A4',
    perk: 'Bảo hành bàn tiệc & Thử vị tận nơi',
    popularCake: 'Bánh Cưới Hoàng Gia Dát Vàng, Bánh Thôi Nôi Thơ Mộng',
  },
  {
    id: 'maison-de-gateaux',
    name: 'Maison de Gâteaux',
    tagline: 'Nghệ Nhân Bánh Kem Tươi & Trái Cây Nhập Khẩu',
    badge: 'Top Reviewer Choice',
    badgeColor: 'bg-emerald-600 text-white',
    location: '88 Tú Xương, Phường Võ Thị Sáu, Quận 3, TP. Hồ Chí Minh',
    city: 'hcm',
    chef: 'Chef Hoàng Nam',
    chefRole: 'Bếp trưởng Pâtisserie 12 năm kinh nghiệm',
    rating: 4.8,
    reviewsCount: 280,
    ordersCount: 1280,
    specialty: 'Kem tươi whipping Anchor béo thanh, dâu tây Đà Lạt chuẩn VietGAP',
    deliverySla: 'Giao hàng xe lạnh 4°C • Kèm thiệp thư pháp viết tay',
    escrowBadge: 'Bảo chứng cọc SweetCake Escrow 100%',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDrd6k8AxdXIpcvUew_MOuWPXERmixyGoGEMSbfRrr2D_NjHNcEfpwO6YmdXvHeBa1Z2RngGb9XmrNj0ZOGL3sN-FAYCvXwCJJKfU7Yp8EabBcjG9dEXYq4nYAN23G4LYhRnmY1pXcqZzK_SmfHOwjKhFKTwsm8fdLQNSiVRu6hg9u1GLpNlwMR4ddt5aAHza-WulOSntXT0apE-cvO0trXucNDl7cTwV9HkUHIgfK-5Y15ik_vKmN4',
    perk: 'Trái cây hữu cơ tươi mới trong ngày',
    popularCake: 'Bánh Kem Bắp Phô Mai & Bánh Dâu Tây Tuyết Trắng',
  },
  {
    id: 'artisan-sweet-atelier',
    name: 'Artisan Sweet Atelier',
    tagline: 'Chuyên Bánh Healthy - Thuần Chay & Ăn Kiêng',
    badge: 'Healthy & Keto Certified',
    badgeColor: 'bg-teal-700 text-white',
    location: '12 Lê Lợi, P. Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    city: 'hcm',
    chef: 'Chef Thu Thảo',
    chefRole: 'Chuyên gia dinh dưỡng và bánh ngọt ít calo',
    rating: 4.9,
    reviewsCount: 195,
    ordersCount: 890,
    specialty: 'Bột hạnh nhân hữu cơ, đường ăn kiêng Isomalt, không chất bảo quản',
    deliverySla: 'Giao chuẩn từng phút • Tặng kèm dao nĩa gỗ tự hủy cao cấp',
    escrowBadge: 'Bảo chứng cọc SweetCake Escrow 100%',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDOuoB1YkEmcnOu28QdxPh8PrBoZw6WU8gax7ow8hE0gMD6xJ8-R_v1vTHO8r0X4m7p__Ja6LLbbgOKpgDK9a-iBDe36sW5Kbq37nXat7eOjQN9RbziT_MUglfGzAF5XDVob0D3S9d0eqeXMfCKWxkxg1LH2324NgXF33F6nf9zmR782zUPGa_CIU_2kIs3d5txJsLeo9K8YcqSs-yUpUrdr6QGU1APz3q6SawD_IxKK_RPdwKcy0pM',
    perk: 'Bánh ăn kiêng ít ngọt chuẩn 100%',
    popularCake: 'Bánh Mousse Bơ Hạt Dẻ Keto, Bánh Carrot Cake Thuần Chay',
  },
]
;

export const MOCK_STORES = STORES;

export const PARTNER_BAKERIES = [
  {
    id: 1,
    name: 'La Crème Pâtisserie',
    badge: 'Top Tiệm Bánh 2024',
    location: 'Quận 1, TP.HCM',
    city: 'hcm',
    subtitle: 'Chứng nhận Nghệ Nhân Bếp Bánh Pháp',
    subtitleIcon: 'military_tech',
    description:
      'Chuyên dòng Entremet cao cấp, 100% bơ Elle & Vire và socola Valrhona thượng hạng. Nướng bánh mới lúc 5h sáng mỗi ngày.',
    rating: '4.9 (320+ đánh giá)',
    orderStat: '1.800+ đơn',
    orderIcon: 'order_approve',
    highlightLabel: 'Bếp trưởng nghệ nhân:',
    highlightValue: 'Chef Jean-Luc Laurent & Chef Mai Anh',
    perk: 'Xe lạnh 4°C - 6°C',
    perkIcon: 'ac_unit',
    image:
      'https://lh3.googleusercontent.com/aida/AEtjO1UW-Pqje1qQ27WocOmEF6z8uQbX4Pu7dER_Li586FmA7D-SZPtELbM4diNLey0TATd7BWeyBRVp0BJyiwRQ_Yj2o8ZvjU1gga_5DYXFHmRARECApBa-Pknbu-F_C4RsJvPsxZur94CVef_-mhMUtBA5pqCBm39qRgn4zALShBi4iNWkPvOaQa9bTIcfaPbq4eDVHCaFKq1lgnsEbgULw4G-0rsbYDlzqjGcSoKiajpNsUeCjPnRs_qaS3o',
  },
  {
    id: 2,
    name: 'Sweet Bakery Studio',
    badge: 'Tiệm Sáng Tạo Của Năm',
    location: 'Quận Bình Thạnh, TP.HCM',
    city: 'hcm',
    subtitle: 'Bậc Thầy Bánh Tạo Hình AI & 3D',
    subtitleIcon: 'auto_awesome',
    description:
      'Tiên phong nhận làm bánh bám sát mẫu render AI với tỷ lệ khớp hình dáng >95%. Cốt Chiffon Nhật Bản mềm mượt ít ngọt.',
    rating: '4.9 (420+ đơn)',
    orderStat: 'Khớp AI >95%',
    orderIcon: 'workspace_premium',
    highlightLabel: 'Thế mạnh vượt trội:',
    highlightValue: 'Fondant nhập khẩu không ngọt gắt & Màu thực phẩm hữu cơ',
    perk: 'Nhận đơn gấp 3H',
    perkIcon: 'bolt',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBwa0x2Pq4PQpZabCVw-oPcl9Kx3AjY8Se4w5V-yM-Cwjrjxd8jba5hv0SPnDkxM_eLtOKLaCNuUDDl6uyQ3slRL0zdoHgazEbhQZgxplLn5ErWpu6LuqSG2cmZUHp2Nrju8F1zOHGfkAEVgsYsLzhyRxlWHDt4rfoMRrrml9EHVVSLAZOB7ORzGf7oOQ614QKeV2tziVXLp5eM7BTdXQBgQysd-nJGwi2Xbb1EPsZ3vM92r3FrOp0B',
  },
  {
    id: 3,
    name: 'Moon Cake Haute Atelier',
    badge: 'Le Cordon Bleu Certified',
    location: 'Quận 2, TP.HCM',
    city: 'hcm',
    subtitle: 'Bánh Kem Sự Kiện & Lễ Cưới',
    subtitleIcon: 'diamond',
    description:
      'Chuyên thiết kế bánh tiệc cưới nhiều tầng lộng lẫy, phối hoa tươi ngoại nhập, macaron thủ công và dát vàng lá ăn được cao cấp.',
    rating: '5.0 (310+ đánh giá 5★)',
    orderStat: 'Xe Lạnh Chuẩn 4°C',
    orderIcon: 'directions_car',
    highlightLabel: 'Dịch vụ đặc biệt:',
    highlightValue: 'Thử vị bánh tận nơi & Thiết kế demo theo chủ đề tiệc',
    perk: 'Bảo hành bàn tiệc',
    perkIcon: 'verified_user',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAbKBS4iuDLDnNj39sedRAM0tSTf90WV0cMtcL1D83J6gCbPWydfHBUx5Vm4AG2wdIJMx0mqVbO5FFktujBONg-xMsmbOSQ-XXqnuTzs_g6OFMgViOgssR3DE9ttoSgkr1Shnt27IVsGw4mZqhmg6xb23szp3_uMuwaK1KAfJwvX-iELmSlnPOkMeTrzZIMJPvIe7VjLNP4s2781KDXemDfKkBVq2wtMqZS8e_AAubIg9VZCOc8z-A4',
  },
];
