export const MOCK_VOUCHERS = [
  {
    id: 'v-sweetcake-50k',
    code: 'SWEETCAKE50K',
    title: 'Giảm 50.000đ Đơn Đầu Tiên',
    description: 'Áp dụng cho tất cả mẫu bánh kem & bento sinh nhật trên hệ thống SweetCake.',
    discountType: 'fixed', // 'fixed' | 'percent'
    discountValue: 50000,
    minOrderValue: 300000,
    maxDiscount: 50000,
    expiryDate: '2026-12-31',
    category: 'system', // 'system' | 'freeship' | 'store' | 'escrow'
    storeName: 'SweetCake Platform',
    badgeText: 'HOT',
    badgeColor: 'bg-primary text-white',
    usageCount: '1.2k lượt dùng',
  },
  {
    id: 'v-freeship-30k',
    code: 'FREESHIP30K',
    title: 'Miễn Phí Vận Chuyển Xe Lạnh 4°C',
    description: 'Tối đa 30.000đ cho dịch vụ giao bánh xe lạnh bảo quản chuyên dụng.',
    discountType: 'fixed',
    discountValue: 30000,
    minOrderValue: 200000,
    maxDiscount: 30000,
    expiryDate: '2026-11-30',
    category: 'freeship',
    storeName: 'Toàn Quốc',
    badgeText: 'FREESHIP XE LẠNH',
    badgeColor: 'bg-secondary text-white',
    usageCount: '3.8k lượt dùng',
  },
  {
    id: 'v-patisserie-10',
    code: 'PATISSERIE10',
    title: 'Ưu Đãi 10% Từ Xưởng La Crème',
    description: 'Giảm 10% tối đa 100.000đ cho dòng bánh Entremet & Mousse Pháp.',
    discountType: 'percent',
    discountValue: 10,
    minOrderValue: 500000,
    maxDiscount: 100000,
    expiryDate: '2026-10-31',
    category: 'store',
    storeName: 'La Crème Pâtisserie',
    badgeText: 'TIỆM 5 SAO',
    badgeColor: 'bg-amber-600 text-white',
    usageCount: '450 lượt dùng',
  },
  {
    id: 'v-escrow-100k',
    code: 'ESCROW100K',
    title: 'Voucher Đảm Bảo Escrow 100K',
    description: 'Voucher ưu đãi bồi hoàn & tri ân bảo hộ giao dịch an tâm 100%.',
    discountType: 'fixed',
    discountValue: 100000,
    minOrderValue: 600000,
    maxDiscount: 100000,
    expiryDate: '2026-12-31',
    category: 'escrow',
    storeName: 'Escrow Vault Guaranteed',
    badgeText: 'BẢO VỆ 100%',
    badgeColor: 'bg-emerald-700 text-white',
    usageCount: '890 lượt dùng',
  },
  {
    id: 'v-vip-200k',
    code: 'VIPLOVE200K',
    title: 'Đặc Quyền Khách Hàng VIP - 200K',
    description: 'Giảm ngay 200.000đ cho đơn tiệc cưới, sự kiện hoặc bánh nghệ thuật trên 1.500.000đ.',
    discountType: 'fixed',
    discountValue: 200000,
    minOrderValue: 1500000,
    maxDiscount: 200000,
    expiryDate: '2026-12-31',
    category: 'system',
    storeName: 'SweetCake VIP Club',
    badgeText: 'ĐẶC QUYỀN VIP',
    badgeColor: 'bg-purple-700 text-white',
    usageCount: '320 lượt dùng',
  },
]
